version: '3.3'
services:
  mysql:
    image: mysql:8.0.22
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - mpt-db:/var/lib/mysql
# Names our volume
volumes:
  mpt-db:
    external: true
